import type { Lead, Payment } from "./types";

const now = new Date();
const iso = (daysAgo: number) =>
  new Date(now.getTime() - daysAgo * 86400000).toISOString();

export const demoLeads: Lead[] = [
  {
    id: "demo-1",
    full_name: "Paola Méndez",
    phone: "+502 5683 7696",
    email: "",
    origin: "Bot",
    product: "Code-Up",
    stage: "interesado",
    interest: "alto",
    deal_amount: 2500,
    payment_method: "Transferencia",
    next_contact_at: iso(-1).slice(0, 10),
    notes: "Interesada en los Code-Up. Enviar detalles del próximo grupo.",
    created_at: iso(0),
    updated_at: iso(0),
  },
  {
    id: "demo-2",
    full_name: "Iván Díaz",
    phone: "+502 3569 4386",
    email: "",
    origin: "Bot",
    product: "Taller de IA",
    stage: "visita",
    interest: "alto",
    deal_amount: 2500,
    payment_method: "",
    next_contact_at: iso(0).slice(0, 10),
    notes: "Pidió información; coordinar visita.",
    created_at: iso(4),
    updated_at: iso(1),
  },
  {
    id: "demo-3",
    full_name: "Sandra Ortiz",
    phone: "+502 4215 8785",
    email: "",
    origin: "Instagram",
    product: "Taller de IA",
    stage: "contactado",
    interest: "medio",
    deal_amount: 2500,
    payment_method: "",
    next_contact_at: iso(2).slice(0, 10),
    notes: "Interesada, pero necesita revisar disponibilidad.",
    created_at: iso(8),
    updated_at: iso(2),
  },
  {
    id: "demo-4",
    full_name: "Carlos Alvarado",
    phone: "+502 5216 3048",
    email: "",
    origin: "Bot",
    product: "Taller de IA",
    stage: "inscrito",
    interest: "alto",
    deal_amount: 2500,
    payment_method: "Transferencia",
    next_contact_at: "",
    notes: "Inscripción confirmada.",
    created_at: iso(18),
    updated_at: iso(3),
  },
  {
    id: "demo-5",
    full_name: "Flor Rodas",
    phone: "+502 4121 9576",
    email: "",
    origin: "Referido",
    product: "Taller de IA",
    stage: "interesado",
    interest: "alto",
    deal_amount: 6500,
    payment_method: "Financiamiento",
    next_contact_at: iso(-2).slice(0, 10),
    notes: "Consulta por descuento para tres personas.",
    created_at: iso(2),
    updated_at: iso(0),
  },
  {
    id: "demo-6",
    full_name: "Marilú Castillo",
    phone: "+502 5694 5473",
    email: "",
    origin: "Bot",
    product: "Taller de IA",
    stage: "nuevo",
    interest: "sin_clasificar",
    deal_amount: 2500,
    payment_method: "",
    next_contact_at: iso(0).slice(0, 10),
    notes: "Solicitó información del taller.",
    created_at: iso(0),
    updated_at: iso(0),
  },
  {
    id: "demo-7",
    full_name: "Benjamín Elías",
    phone: "+502 5016 1944",
    email: "",
    origin: "Facebook",
    product: "Code-Up",
    stage: "perdido",
    interest: "bajo",
    deal_amount: 2500,
    payment_method: "",
    next_contact_at: "",
    notes: "No puede asistir en las fechas actuales.",
    created_at: iso(26),
    updated_at: iso(12),
  },
  {
    id: "demo-8",
    full_name: "María José Hernández",
    phone: "+502 4753 2735",
    email: "",
    origin: "Bot",
    product: "Taller de IA",
    stage: "inscrito",
    interest: "alto",
    deal_amount: 2500,
    payment_method: "Transferencia",
    next_contact_at: "",
    notes: "Pago recibido.",
    created_at: iso(31),
    updated_at: iso(5),
  },
  {
    id: "demo-9",
    full_name: "Roberto Guerra",
    phone: "+502 3777 3244",
    email: "",
    origin: "Instagram",
    product: "Analítica de datos",
    stage: "interesado",
    interest: "medio",
    deal_amount: 3200,
    payment_method: "Tarjeta",
    next_contact_at: iso(3).slice(0, 10),
    notes: "Solicitó temario.",
    created_at: iso(12),
    updated_at: iso(1),
  },
  {
    id: "demo-10",
    full_name: "Astrid López",
    phone: "+502 5462 3317",
    email: "",
    origin: "Bot",
    product: "Taller de IA",
    stage: "contactado",
    interest: "bajo",
    deal_amount: 2500,
    payment_method: "",
    next_contact_at: iso(-3).slice(0, 10),
    notes: "No contestó la llamada; reintentar.",
    created_at: iso(15),
    updated_at: iso(4),
  },
  {
    id: "demo-11",
    full_name: "William Agustín",
    phone: "+502 5014 7207",
    email: "",
    origin: "Referido",
    product: "Code-Up",
    stage: "nuevo",
    interest: "sin_clasificar",
    deal_amount: 2500,
    payment_method: "",
    next_contact_at: iso(0).slice(0, 10),
    notes: "",
    created_at: iso(1),
    updated_at: iso(1),
  },
  {
    id: "demo-12",
    full_name: "Patricia Gómez",
    phone: "+502 3520 3789",
    email: "",
    origin: "Facebook",
    product: "Taller de IA",
    stage: "inscrito",
    interest: "alto",
    deal_amount: 2500,
    payment_method: "Efectivo",
    next_contact_at: "",
    notes: "Inscripción confirmada en campus.",
    created_at: iso(42),
    updated_at: iso(8),
  },
];

export const demoPayments: Payment[] = [
  {
    id: "pay-1",
    lead_id: "demo-4",
    amount: 2500,
    method: "Transferencia",
    status: "pagado",
    due_date: "",
    paid_at: iso(3),
    reference: "Pago de inscripción",
    created_at: iso(3),
  },
  {
    id: "pay-2",
    lead_id: "demo-8",
    amount: 1500,
    method: "Transferencia",
    status: "pagado",
    due_date: "",
    paid_at: iso(5),
    reference: "Primer pago",
    created_at: iso(5),
  },
  {
    id: "pay-3",
    lead_id: "demo-8",
    amount: 1000,
    method: "Transferencia",
    status: "pendiente",
    due_date: iso(-8).slice(0, 10),
    paid_at: "",
    reference: "Saldo pendiente",
    created_at: iso(5),
  },
  {
    id: "pay-4",
    lead_id: "demo-12",
    amount: 2500,
    method: "Efectivo",
    status: "pagado",
    due_date: "",
    paid_at: iso(8),
    reference: "Pago completo",
    created_at: iso(8),
  },
];
